version: '3.8'

services:
  nextjs:
    build: ./app
    container_name: nextjs-app
    expose:
      - "3000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/webroot:/var/www/certbot
      - ./certbot/letsencrypt:/etc/letsencrypt
    depends_on:
      - nextjs
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/webroot:/var/www/certbot
      - ./certbot/letsencrypt:/etc/letsencrypt
    entrypoint: "/bin/sh -c"
    command: >
      "certbot certonly --webroot 
       --webroot-path=/var/www/certbot 
       --email john@mutant.ae 
       --agree-tos 
       --no-eff-email 
       -d ads.aesthetics.aliice.space"
